config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Blorgh::Engine, at: "/blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unicorn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to 'Articles', blorgh_path, class: "nav-link"%>
      <% if user_signed_in? %>
      <%= link_to 'My Reports', blorgh.reports_path, class: "nav-link"%>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <p>Welcome <%= current_user.email %></p>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-link"%>
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<p>Welcome to Blorgh</p>